# Generated by Django 4.2.6 on 2023-10-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_vendedor_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='observacao',
            field=models.CharField(default='Sem observações', max_length=200, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telefone',
            field=models.CharField(blank=True, help_text='(86) 99999-9999', max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('ativo', models.BooleanField(default=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='vendas.vendedor')),
            ],
        ),
    ]
