# Generated by Django 4.2.6 on 2023-10-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_vendedor_options_alter_vendedor_observacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto'},
        ),
        migrations.AddField(
            model_name='vendedor',
            name='local',
            field=models.CharField(choices=[('a', 'Prédio A'), ('b1', 'Prédio B1'), ('b2', 'Prédio B2'), ('b3', 'Prédio B3'), ('c1', 'Prédio C1'), ('c2', 'Prédio C2'), ('c3', 'Prédio C3')], default='b2', max_length=100, verbose_name='Prédio'),
        ),
    ]
